//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 03:53:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www3.medical.philips.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sierraecg.schema;
