//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:37 PM EDT 
//


package org.sierraecg.schema.jaxb._1_03;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="heartrate">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPErate">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanprint">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqrsdur">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqtint">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqtc">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="i40frontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="t40frontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="qrsfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="phorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="i40horizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="t40horizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="qrshorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sthorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="thorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="arrhyflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="editedflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heartrate",
    "meanprint",
    "meanqrsdur",
    "meanqtint",
    "meanqtc",
    "pfrontaxis",
    "i40Frontaxis",
    "t40Frontaxis",
    "qrsfrontaxis",
    "stfrontaxis",
    "tfrontaxis",
    "phorizaxis",
    "i40Horizaxis",
    "t40Horizaxis",
    "qrshorizaxis",
    "sthorizaxis",
    "thorizaxis"
})
@XmlRootElement(name = "interpretationmeasurements")
public class Interpretationmeasurements {

    @XmlElement(required = true)
    protected Interpretationmeasurements.Heartrate heartrate;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Meanprint meanprint;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Meanqrsdur meanqrsdur;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Meanqtint meanqtint;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Meanqtc meanqtc;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Pfrontaxis pfrontaxis;
    @XmlElement(name = "i40frontaxis", required = true)
    protected Interpretationmeasurements.I40Frontaxis i40Frontaxis;
    @XmlElement(name = "t40frontaxis", required = true)
    protected Interpretationmeasurements.T40Frontaxis t40Frontaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Qrsfrontaxis qrsfrontaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Stfrontaxis stfrontaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Tfrontaxis tfrontaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Phorizaxis phorizaxis;
    @XmlElement(name = "i40horizaxis", required = true)
    protected Interpretationmeasurements.I40Horizaxis i40Horizaxis;
    @XmlElement(name = "t40horizaxis", required = true)
    protected Interpretationmeasurements.T40Horizaxis t40Horizaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Qrshorizaxis qrshorizaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Sthorizaxis sthorizaxis;
    @XmlElement(required = true)
    protected Interpretationmeasurements.Thorizaxis thorizaxis;
    @XmlAttribute(name = "arrhyflag", required = true)
    protected TYPEflag arrhyflag;
    @XmlAttribute(name = "editedflag", required = true)
    protected TYPEflag editedflag;

    /**
     * Gets the value of the heartrate property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Heartrate }
     *     
     */
    public Interpretationmeasurements.Heartrate getHeartrate() {
        return heartrate;
    }

    /**
     * Sets the value of the heartrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Heartrate }
     *     
     */
    public void setHeartrate(Interpretationmeasurements.Heartrate value) {
        this.heartrate = value;
    }

    /**
     * Gets the value of the meanprint property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Meanprint }
     *     
     */
    public Interpretationmeasurements.Meanprint getMeanprint() {
        return meanprint;
    }

    /**
     * Sets the value of the meanprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Meanprint }
     *     
     */
    public void setMeanprint(Interpretationmeasurements.Meanprint value) {
        this.meanprint = value;
    }

    /**
     * Gets the value of the meanqrsdur property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Meanqrsdur }
     *     
     */
    public Interpretationmeasurements.Meanqrsdur getMeanqrsdur() {
        return meanqrsdur;
    }

    /**
     * Sets the value of the meanqrsdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Meanqrsdur }
     *     
     */
    public void setMeanqrsdur(Interpretationmeasurements.Meanqrsdur value) {
        this.meanqrsdur = value;
    }

    /**
     * Gets the value of the meanqtint property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Meanqtint }
     *     
     */
    public Interpretationmeasurements.Meanqtint getMeanqtint() {
        return meanqtint;
    }

    /**
     * Sets the value of the meanqtint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Meanqtint }
     *     
     */
    public void setMeanqtint(Interpretationmeasurements.Meanqtint value) {
        this.meanqtint = value;
    }

    /**
     * Gets the value of the meanqtc property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Meanqtc }
     *     
     */
    public Interpretationmeasurements.Meanqtc getMeanqtc() {
        return meanqtc;
    }

    /**
     * Sets the value of the meanqtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Meanqtc }
     *     
     */
    public void setMeanqtc(Interpretationmeasurements.Meanqtc value) {
        this.meanqtc = value;
    }

    /**
     * Gets the value of the pfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Pfrontaxis }
     *     
     */
    public Interpretationmeasurements.Pfrontaxis getPfrontaxis() {
        return pfrontaxis;
    }

    /**
     * Sets the value of the pfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Pfrontaxis }
     *     
     */
    public void setPfrontaxis(Interpretationmeasurements.Pfrontaxis value) {
        this.pfrontaxis = value;
    }

    /**
     * Gets the value of the i40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.I40Frontaxis }
     *     
     */
    public Interpretationmeasurements.I40Frontaxis getI40Frontaxis() {
        return i40Frontaxis;
    }

    /**
     * Sets the value of the i40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.I40Frontaxis }
     *     
     */
    public void setI40Frontaxis(Interpretationmeasurements.I40Frontaxis value) {
        this.i40Frontaxis = value;
    }

    /**
     * Gets the value of the t40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.T40Frontaxis }
     *     
     */
    public Interpretationmeasurements.T40Frontaxis getT40Frontaxis() {
        return t40Frontaxis;
    }

    /**
     * Sets the value of the t40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.T40Frontaxis }
     *     
     */
    public void setT40Frontaxis(Interpretationmeasurements.T40Frontaxis value) {
        this.t40Frontaxis = value;
    }

    /**
     * Gets the value of the qrsfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Qrsfrontaxis }
     *     
     */
    public Interpretationmeasurements.Qrsfrontaxis getQrsfrontaxis() {
        return qrsfrontaxis;
    }

    /**
     * Sets the value of the qrsfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Qrsfrontaxis }
     *     
     */
    public void setQrsfrontaxis(Interpretationmeasurements.Qrsfrontaxis value) {
        this.qrsfrontaxis = value;
    }

    /**
     * Gets the value of the stfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Stfrontaxis }
     *     
     */
    public Interpretationmeasurements.Stfrontaxis getStfrontaxis() {
        return stfrontaxis;
    }

    /**
     * Sets the value of the stfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Stfrontaxis }
     *     
     */
    public void setStfrontaxis(Interpretationmeasurements.Stfrontaxis value) {
        this.stfrontaxis = value;
    }

    /**
     * Gets the value of the tfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Tfrontaxis }
     *     
     */
    public Interpretationmeasurements.Tfrontaxis getTfrontaxis() {
        return tfrontaxis;
    }

    /**
     * Sets the value of the tfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Tfrontaxis }
     *     
     */
    public void setTfrontaxis(Interpretationmeasurements.Tfrontaxis value) {
        this.tfrontaxis = value;
    }

    /**
     * Gets the value of the phorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Phorizaxis }
     *     
     */
    public Interpretationmeasurements.Phorizaxis getPhorizaxis() {
        return phorizaxis;
    }

    /**
     * Sets the value of the phorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Phorizaxis }
     *     
     */
    public void setPhorizaxis(Interpretationmeasurements.Phorizaxis value) {
        this.phorizaxis = value;
    }

    /**
     * Gets the value of the i40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.I40Horizaxis }
     *     
     */
    public Interpretationmeasurements.I40Horizaxis getI40Horizaxis() {
        return i40Horizaxis;
    }

    /**
     * Sets the value of the i40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.I40Horizaxis }
     *     
     */
    public void setI40Horizaxis(Interpretationmeasurements.I40Horizaxis value) {
        this.i40Horizaxis = value;
    }

    /**
     * Gets the value of the t40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.T40Horizaxis }
     *     
     */
    public Interpretationmeasurements.T40Horizaxis getT40Horizaxis() {
        return t40Horizaxis;
    }

    /**
     * Sets the value of the t40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.T40Horizaxis }
     *     
     */
    public void setT40Horizaxis(Interpretationmeasurements.T40Horizaxis value) {
        this.t40Horizaxis = value;
    }

    /**
     * Gets the value of the qrshorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Qrshorizaxis }
     *     
     */
    public Interpretationmeasurements.Qrshorizaxis getQrshorizaxis() {
        return qrshorizaxis;
    }

    /**
     * Sets the value of the qrshorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Qrshorizaxis }
     *     
     */
    public void setQrshorizaxis(Interpretationmeasurements.Qrshorizaxis value) {
        this.qrshorizaxis = value;
    }

    /**
     * Gets the value of the sthorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Sthorizaxis }
     *     
     */
    public Interpretationmeasurements.Sthorizaxis getSthorizaxis() {
        return sthorizaxis;
    }

    /**
     * Sets the value of the sthorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Sthorizaxis }
     *     
     */
    public void setSthorizaxis(Interpretationmeasurements.Sthorizaxis value) {
        this.sthorizaxis = value;
    }

    /**
     * Gets the value of the thorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretationmeasurements.Thorizaxis }
     *     
     */
    public Interpretationmeasurements.Thorizaxis getThorizaxis() {
        return thorizaxis;
    }

    /**
     * Sets the value of the thorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretationmeasurements.Thorizaxis }
     *     
     */
    public void setThorizaxis(Interpretationmeasurements.Thorizaxis value) {
        this.thorizaxis = value;
    }

    /**
     * Gets the value of the arrhyflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getArrhyflag() {
        return arrhyflag;
    }

    /**
     * Sets the value of the arrhyflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setArrhyflag(TYPEflag value) {
        this.arrhyflag = value;
    }

    /**
     * Gets the value of the editedflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getEditedflag() {
        return editedflag;
    }

    /**
     * Sets the value of the editedflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setEditedflag(TYPEflag value) {
        this.editedflag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPErate">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Heartrate {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class I40Frontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class I40Horizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Meanprint {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Meanqrsdur {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Meanqtc {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Meanqtint {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Pfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Phorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Qrsfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Qrshorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Stfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Sthorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class T40Frontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class T40Horizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Tfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Thorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }

}
