//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:37 PM EDT 
//


package org.sierraecg.schema.jaxb._1_03;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}pacepulses" minOccurs="0"/>
 *         &lt;group ref="{http://www3.medical.philips.com}leadmeasurement.elements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="leadname" use="required" type="{http://www3.medical.philips.com}TYPEleadname" />
 *       &lt;attribute name="pexistflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="pmeasflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="pnotchflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="qrsexistflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="qrsspikeflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="qrsmeasflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="qrsnotchflag" use="required" type="{http://www3.medical.philips.com}TYPEflag2" />
 *       &lt;attribute name="qrsdeltaflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="stexistflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="stmeasflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="texistflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="tmeasflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="tnotchflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="atrialpaceflag" use="required" type="{http://www3.medical.philips.com}TYPEflag3" />
 *       &lt;attribute name="ventpaceflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pacepulses",
    "leadqualitystates",
    "pamp",
    "pdur",
    "parea",
    "ppamp",
    "ppdur",
    "ppppdur",
    "pparea",
    "pppparea",
    "qamp",
    "qdur",
    "ramp",
    "rdur",
    "samp",
    "sdur",
    "rpamp",
    "rpdur",
    "spamp",
    "spdur",
    "vat",
    "qrsppk",
    "qrsdur",
    "qrsarea",
    "ston",
    "stmid",
    "st80",
    "stend",
    "stdur",
    "stslope",
    "stshape",
    "tamp",
    "tdur",
    "tarea",
    "tpamp",
    "tptpdur",
    "tpdur",
    "tparea",
    "tptparea",
    "print",
    "prseg",
    "qtint"
})
@XmlRootElement(name = "leadmeasurement")
public class Leadmeasurement {

    protected Pacepulses pacepulses;
    @XmlElement(required = true)
    protected Leadqualitystates leadqualitystates;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String parea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ppamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ppdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ppppdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pparea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pppparea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ramp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String samp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rpamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rpdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String spamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String spdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String vat;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qrsppk;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qrsdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qrsarea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ston;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stmid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String st80;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stend;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stslope;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TYPEstshape stshape;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tarea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tpamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tptpdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tpdur;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tparea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tptparea;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String print;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prseg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String qtint;
    @XmlAttribute(name = "leadname", required = true)
    protected String leadname;
    @XmlAttribute(name = "pexistflag", required = true)
    protected TYPEflag pexistflag;
    @XmlAttribute(name = "pmeasflag", required = true)
    protected TYPEflag pmeasflag;
    @XmlAttribute(name = "pnotchflag", required = true)
    protected TYPEflag pnotchflag;
    @XmlAttribute(name = "qrsexistflag", required = true)
    protected TYPEflag qrsexistflag;
    @XmlAttribute(name = "qrsspikeflag", required = true)
    protected TYPEflag qrsspikeflag;
    @XmlAttribute(name = "qrsmeasflag", required = true)
    protected TYPEflag qrsmeasflag;
    @XmlAttribute(name = "qrsnotchflag", required = true)
    protected TYPEflag2 qrsnotchflag;
    @XmlAttribute(name = "qrsdeltaflag", required = true)
    protected TYPEflag qrsdeltaflag;
    @XmlAttribute(name = "stexistflag", required = true)
    protected TYPEflag stexistflag;
    @XmlAttribute(name = "stmeasflag", required = true)
    protected TYPEflag stmeasflag;
    @XmlAttribute(name = "texistflag", required = true)
    protected TYPEflag texistflag;
    @XmlAttribute(name = "tmeasflag", required = true)
    protected TYPEflag tmeasflag;
    @XmlAttribute(name = "tnotchflag", required = true)
    protected TYPEflag tnotchflag;
    @XmlAttribute(name = "atrialpaceflag", required = true)
    protected TYPEflag3 atrialpaceflag;
    @XmlAttribute(name = "ventpaceflag", required = true)
    protected TYPEflag ventpaceflag;

    /**
     * Gets the value of the pacepulses property.
     * 
     * @return
     *     possible object is
     *     {@link Pacepulses }
     *     
     */
    public Pacepulses getPacepulses() {
        return pacepulses;
    }

    /**
     * Sets the value of the pacepulses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pacepulses }
     *     
     */
    public void setPacepulses(Pacepulses value) {
        this.pacepulses = value;
    }

    /**
     * Gets the value of the leadqualitystates property.
     * 
     * @return
     *     possible object is
     *     {@link Leadqualitystates }
     *     
     */
    public Leadqualitystates getLeadqualitystates() {
        return leadqualitystates;
    }

    /**
     * Sets the value of the leadqualitystates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leadqualitystates }
     *     
     */
    public void setLeadqualitystates(Leadqualitystates value) {
        this.leadqualitystates = value;
    }

    /**
     * Gets the value of the pamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPamp() {
        return pamp;
    }

    /**
     * Sets the value of the pamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPamp(String value) {
        this.pamp = value;
    }

    /**
     * Gets the value of the pdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdur() {
        return pdur;
    }

    /**
     * Sets the value of the pdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdur(String value) {
        this.pdur = value;
    }

    /**
     * Gets the value of the parea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParea() {
        return parea;
    }

    /**
     * Sets the value of the parea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParea(String value) {
        this.parea = value;
    }

    /**
     * Gets the value of the ppamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpamp() {
        return ppamp;
    }

    /**
     * Sets the value of the ppamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpamp(String value) {
        this.ppamp = value;
    }

    /**
     * Gets the value of the ppdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpdur() {
        return ppdur;
    }

    /**
     * Sets the value of the ppdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpdur(String value) {
        this.ppdur = value;
    }

    /**
     * Gets the value of the ppppdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpppdur() {
        return ppppdur;
    }

    /**
     * Sets the value of the ppppdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpppdur(String value) {
        this.ppppdur = value;
    }

    /**
     * Gets the value of the pparea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPparea() {
        return pparea;
    }

    /**
     * Sets the value of the pparea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPparea(String value) {
        this.pparea = value;
    }

    /**
     * Gets the value of the pppparea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPppparea() {
        return pppparea;
    }

    /**
     * Sets the value of the pppparea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPppparea(String value) {
        this.pppparea = value;
    }

    /**
     * Gets the value of the qamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQamp() {
        return qamp;
    }

    /**
     * Sets the value of the qamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQamp(String value) {
        this.qamp = value;
    }

    /**
     * Gets the value of the qdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQdur() {
        return qdur;
    }

    /**
     * Sets the value of the qdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQdur(String value) {
        this.qdur = value;
    }

    /**
     * Gets the value of the ramp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRamp() {
        return ramp;
    }

    /**
     * Sets the value of the ramp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRamp(String value) {
        this.ramp = value;
    }

    /**
     * Gets the value of the rdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRdur() {
        return rdur;
    }

    /**
     * Sets the value of the rdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRdur(String value) {
        this.rdur = value;
    }

    /**
     * Gets the value of the samp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamp() {
        return samp;
    }

    /**
     * Sets the value of the samp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamp(String value) {
        this.samp = value;
    }

    /**
     * Gets the value of the sdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdur() {
        return sdur;
    }

    /**
     * Sets the value of the sdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdur(String value) {
        this.sdur = value;
    }

    /**
     * Gets the value of the rpamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpamp() {
        return rpamp;
    }

    /**
     * Sets the value of the rpamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpamp(String value) {
        this.rpamp = value;
    }

    /**
     * Gets the value of the rpdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpdur() {
        return rpdur;
    }

    /**
     * Sets the value of the rpdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpdur(String value) {
        this.rpdur = value;
    }

    /**
     * Gets the value of the spamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpamp() {
        return spamp;
    }

    /**
     * Sets the value of the spamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpamp(String value) {
        this.spamp = value;
    }

    /**
     * Gets the value of the spdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpdur() {
        return spdur;
    }

    /**
     * Sets the value of the spdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpdur(String value) {
        this.spdur = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVat(String value) {
        this.vat = value;
    }

    /**
     * Gets the value of the qrsppk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrsppk() {
        return qrsppk;
    }

    /**
     * Sets the value of the qrsppk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrsppk(String value) {
        this.qrsppk = value;
    }

    /**
     * Gets the value of the qrsdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrsdur() {
        return qrsdur;
    }

    /**
     * Sets the value of the qrsdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrsdur(String value) {
        this.qrsdur = value;
    }

    /**
     * Gets the value of the qrsarea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrsarea() {
        return qrsarea;
    }

    /**
     * Sets the value of the qrsarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrsarea(String value) {
        this.qrsarea = value;
    }

    /**
     * Gets the value of the ston property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSton() {
        return ston;
    }

    /**
     * Sets the value of the ston property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSton(String value) {
        this.ston = value;
    }

    /**
     * Gets the value of the stmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStmid() {
        return stmid;
    }

    /**
     * Sets the value of the stmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStmid(String value) {
        this.stmid = value;
    }

    /**
     * Gets the value of the st80 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSt80() {
        return st80;
    }

    /**
     * Sets the value of the st80 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSt80(String value) {
        this.st80 = value;
    }

    /**
     * Gets the value of the stend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStend() {
        return stend;
    }

    /**
     * Sets the value of the stend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStend(String value) {
        this.stend = value;
    }

    /**
     * Gets the value of the stdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStdur() {
        return stdur;
    }

    /**
     * Sets the value of the stdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStdur(String value) {
        this.stdur = value;
    }

    /**
     * Gets the value of the stslope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStslope() {
        return stslope;
    }

    /**
     * Sets the value of the stslope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStslope(String value) {
        this.stslope = value;
    }

    /**
     * Gets the value of the stshape property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEstshape }
     *     
     */
    public TYPEstshape getStshape() {
        return stshape;
    }

    /**
     * Sets the value of the stshape property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEstshape }
     *     
     */
    public void setStshape(TYPEstshape value) {
        this.stshape = value;
    }

    /**
     * Gets the value of the tamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTamp() {
        return tamp;
    }

    /**
     * Sets the value of the tamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTamp(String value) {
        this.tamp = value;
    }

    /**
     * Gets the value of the tdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdur() {
        return tdur;
    }

    /**
     * Sets the value of the tdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdur(String value) {
        this.tdur = value;
    }

    /**
     * Gets the value of the tarea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarea() {
        return tarea;
    }

    /**
     * Sets the value of the tarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarea(String value) {
        this.tarea = value;
    }

    /**
     * Gets the value of the tpamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpamp() {
        return tpamp;
    }

    /**
     * Sets the value of the tpamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpamp(String value) {
        this.tpamp = value;
    }

    /**
     * Gets the value of the tptpdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTptpdur() {
        return tptpdur;
    }

    /**
     * Sets the value of the tptpdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTptpdur(String value) {
        this.tptpdur = value;
    }

    /**
     * Gets the value of the tpdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpdur() {
        return tpdur;
    }

    /**
     * Sets the value of the tpdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpdur(String value) {
        this.tpdur = value;
    }

    /**
     * Gets the value of the tparea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTparea() {
        return tparea;
    }

    /**
     * Sets the value of the tparea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTparea(String value) {
        this.tparea = value;
    }

    /**
     * Gets the value of the tptparea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTptparea() {
        return tptparea;
    }

    /**
     * Sets the value of the tptparea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTptparea(String value) {
        this.tptparea = value;
    }

    /**
     * Gets the value of the print property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrint(String value) {
        this.print = value;
    }

    /**
     * Gets the value of the prseg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrseg() {
        return prseg;
    }

    /**
     * Sets the value of the prseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrseg(String value) {
        this.prseg = value;
    }

    /**
     * Gets the value of the qtint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtint() {
        return qtint;
    }

    /**
     * Sets the value of the qtint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtint(String value) {
        this.qtint = value;
    }

    /**
     * Gets the value of the leadname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadname() {
        return leadname;
    }

    /**
     * Sets the value of the leadname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadname(String value) {
        this.leadname = value;
    }

    /**
     * Gets the value of the pexistflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getPexistflag() {
        return pexistflag;
    }

    /**
     * Sets the value of the pexistflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setPexistflag(TYPEflag value) {
        this.pexistflag = value;
    }

    /**
     * Gets the value of the pmeasflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getPmeasflag() {
        return pmeasflag;
    }

    /**
     * Sets the value of the pmeasflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setPmeasflag(TYPEflag value) {
        this.pmeasflag = value;
    }

    /**
     * Gets the value of the pnotchflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getPnotchflag() {
        return pnotchflag;
    }

    /**
     * Sets the value of the pnotchflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setPnotchflag(TYPEflag value) {
        this.pnotchflag = value;
    }

    /**
     * Gets the value of the qrsexistflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getQrsexistflag() {
        return qrsexistflag;
    }

    /**
     * Sets the value of the qrsexistflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setQrsexistflag(TYPEflag value) {
        this.qrsexistflag = value;
    }

    /**
     * Gets the value of the qrsspikeflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getQrsspikeflag() {
        return qrsspikeflag;
    }

    /**
     * Sets the value of the qrsspikeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setQrsspikeflag(TYPEflag value) {
        this.qrsspikeflag = value;
    }

    /**
     * Gets the value of the qrsmeasflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getQrsmeasflag() {
        return qrsmeasflag;
    }

    /**
     * Sets the value of the qrsmeasflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setQrsmeasflag(TYPEflag value) {
        this.qrsmeasflag = value;
    }

    /**
     * Gets the value of the qrsnotchflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag2 }
     *     
     */
    public TYPEflag2 getQrsnotchflag() {
        return qrsnotchflag;
    }

    /**
     * Sets the value of the qrsnotchflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag2 }
     *     
     */
    public void setQrsnotchflag(TYPEflag2 value) {
        this.qrsnotchflag = value;
    }

    /**
     * Gets the value of the qrsdeltaflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getQrsdeltaflag() {
        return qrsdeltaflag;
    }

    /**
     * Sets the value of the qrsdeltaflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setQrsdeltaflag(TYPEflag value) {
        this.qrsdeltaflag = value;
    }

    /**
     * Gets the value of the stexistflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getStexistflag() {
        return stexistflag;
    }

    /**
     * Sets the value of the stexistflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setStexistflag(TYPEflag value) {
        this.stexistflag = value;
    }

    /**
     * Gets the value of the stmeasflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getStmeasflag() {
        return stmeasflag;
    }

    /**
     * Sets the value of the stmeasflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setStmeasflag(TYPEflag value) {
        this.stmeasflag = value;
    }

    /**
     * Gets the value of the texistflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getTexistflag() {
        return texistflag;
    }

    /**
     * Sets the value of the texistflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setTexistflag(TYPEflag value) {
        this.texistflag = value;
    }

    /**
     * Gets the value of the tmeasflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getTmeasflag() {
        return tmeasflag;
    }

    /**
     * Sets the value of the tmeasflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setTmeasflag(TYPEflag value) {
        this.tmeasflag = value;
    }

    /**
     * Gets the value of the tnotchflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getTnotchflag() {
        return tnotchflag;
    }

    /**
     * Sets the value of the tnotchflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setTnotchflag(TYPEflag value) {
        this.tnotchflag = value;
    }

    /**
     * Gets the value of the atrialpaceflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag3 }
     *     
     */
    public TYPEflag3 getAtrialpaceflag() {
        return atrialpaceflag;
    }

    /**
     * Sets the value of the atrialpaceflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag3 }
     *     
     */
    public void setAtrialpaceflag(TYPEflag3 value) {
        this.atrialpaceflag = value;
    }

    /**
     * Gets the value of the ventpaceflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getVentpaceflag() {
        return ventpaceflag;
    }

    /**
     * Sets the value of the ventpaceflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setVentpaceflag(TYPEflag value) {
        this.ventpaceflag = value;
    }

}
