//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:37 PM EDT 
//


package org.sierraecg.schema.jaxb._1_03;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}reporttype"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportdescription"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportformat"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportgain"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportbandwidth"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reporttype",
    "reportdescription",
    "reportformat",
    "reportgain",
    "reportbandwidth"
})
@XmlRootElement(name = "reportinfo")
public class Reportinfo {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TYPEreporttype reporttype;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TYPEreportdescription reportdescription;
    @XmlElement(required = true)
    protected Reportformat reportformat;
    @XmlElement(required = true)
    protected Reportgain reportgain;
    @XmlElement(required = true)
    protected Reportbandwidth reportbandwidth;
    @XmlAttribute(name = "date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;

    /**
     * Gets the value of the reporttype property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEreporttype }
     *     
     */
    public TYPEreporttype getReporttype() {
        return reporttype;
    }

    /**
     * Sets the value of the reporttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEreporttype }
     *     
     */
    public void setReporttype(TYPEreporttype value) {
        this.reporttype = value;
    }

    /**
     * Gets the value of the reportdescription property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEreportdescription }
     *     
     */
    public TYPEreportdescription getReportdescription() {
        return reportdescription;
    }

    /**
     * Sets the value of the reportdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEreportdescription }
     *     
     */
    public void setReportdescription(TYPEreportdescription value) {
        this.reportdescription = value;
    }

    /**
     * Gets the value of the reportformat property.
     * 
     * @return
     *     possible object is
     *     {@link Reportformat }
     *     
     */
    public Reportformat getReportformat() {
        return reportformat;
    }

    /**
     * Sets the value of the reportformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportformat }
     *     
     */
    public void setReportformat(Reportformat value) {
        this.reportformat = value;
    }

    /**
     * Gets the value of the reportgain property.
     * 
     * @return
     *     possible object is
     *     {@link Reportgain }
     *     
     */
    public Reportgain getReportgain() {
        return reportgain;
    }

    /**
     * Sets the value of the reportgain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportgain }
     *     
     */
    public void setReportgain(Reportgain value) {
        this.reportgain = value;
    }

    /**
     * Gets the value of the reportbandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Reportbandwidth }
     *     
     */
    public Reportbandwidth getReportbandwidth() {
        return reportbandwidth;
    }

    /**
     * Sets the value of the reportbandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportbandwidth }
     *     
     */
    public void setReportbandwidth(Reportbandwidth value) {
        this.reportbandwidth = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

}
