//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:37 PM EDT 
//


package org.sierraecg.schema.jaxb._1_03;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TYPEreportdescription.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TYPEreportdescription">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Standard 12 Lead Report"/>
 *     &lt;enumeration value="Standard 12 Lead Report with Mason Likar lead set"/>
 *     &lt;enumeration value="MIDA derived 12 Lead Report"/>
 *     &lt;enumeration value="EASI derived 12 Lead Report"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TYPEreportdescription")
@XmlEnum
public enum TYPEreportdescription {

    @XmlEnumValue("Standard 12 Lead Report")
    STANDARD_12_LEAD_REPORT("Standard 12 Lead Report"),
    @XmlEnumValue("Standard 12 Lead Report with Mason Likar lead set")
    STANDARD_12_LEAD_REPORT_WITH_MASON_LIKAR_LEAD_SET("Standard 12 Lead Report with Mason Likar lead set"),
    @XmlEnumValue("MIDA derived 12 Lead Report")
    MIDA_DERIVED_12_LEAD_REPORT("MIDA derived 12 Lead Report"),
    @XmlEnumValue("EASI derived 12 Lead Report")
    EASI_DERIVED_12_LEAD_REPORT("EASI derived 12 Lead Report");
    private final String value;

    TYPEreportdescription(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TYPEreportdescription fromValue(String v) {
        for (TYPEreportdescription c: TYPEreportdescription.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
