//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beat" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="pon" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                   &lt;element name="poff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                   &lt;element name="qon" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                   &lt;element name="qoff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                   &lt;element name="ton" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                   &lt;element name="toff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beat"
})
@XmlRootElement(name = "beats")
public class Beats {

    protected List<Beats.Beat> beat;

    /**
     * Gets the value of the beat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Beats.Beat }
     * 
     * 
     */
    public List<Beats.Beat> getBeat() {
        if (beat == null) {
            beat = new ArrayList<Beats.Beat>();
        }
        return this.beat;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="pon" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *         &lt;element name="poff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *         &lt;element name="qon" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *         &lt;element name="qoff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *         &lt;element name="ton" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *         &lt;element name="toff" type="{http://www3.medical.philips.com}TYPEfiducial" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "group",
        "pon",
        "poff",
        "qon",
        "qoff",
        "ton",
        "toff"
    })
    public static class Beat {

        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger group;
        @XmlSchemaType(name = "anySimpleType")
        protected String pon;
        @XmlSchemaType(name = "anySimpleType")
        protected String poff;
        @XmlSchemaType(name = "anySimpleType")
        protected String qon;
        @XmlSchemaType(name = "anySimpleType")
        protected String qoff;
        @XmlSchemaType(name = "anySimpleType")
        protected String ton;
        @XmlSchemaType(name = "anySimpleType")
        protected String toff;

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGroup(BigInteger value) {
            this.group = value;
        }

        /**
         * Gets the value of the pon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPon() {
            return pon;
        }

        /**
         * Sets the value of the pon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPon(String value) {
            this.pon = value;
        }

        /**
         * Gets the value of the poff property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoff() {
            return poff;
        }

        /**
         * Sets the value of the poff property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoff(String value) {
            this.poff = value;
        }

        /**
         * Gets the value of the qon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQon() {
            return qon;
        }

        /**
         * Sets the value of the qon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQon(String value) {
            this.qon = value;
        }

        /**
         * Gets the value of the qoff property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQoff() {
            return qoff;
        }

        /**
         * Sets the value of the qoff property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQoff(String value) {
            this.qoff = value;
        }

        /**
         * Gets the value of the ton property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTon() {
            return ton;
        }

        /**
         * Sets the value of the ton property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTon(String value) {
            this.ton = value;
        }

        /**
         * Gets the value of the toff property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToff() {
            return toff;
        }

        /**
         * Sets the value of the toff property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToff(String value) {
            this.toff = value;
        }

    }

}
