//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bradyhrlimit" type="{http://www3.medical.philips.com}TYPEintegerORnull" minOccurs="0"/>
 *         &lt;element name="asianlvhcriteria" type="{http://www3.medical.philips.com}TYPEflag" minOccurs="0"/>
 *         &lt;element name="qualitystmts" type="{http://www3.medical.philips.com}TYPEintegerORnull" minOccurs="0"/>
 *         &lt;element name="sensitivity" type="{http://www3.medical.philips.com}TYPEintegerORnull" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}configsetting" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bradyhrlimit",
    "asianlvhcriteria",
    "qualitystmts",
    "sensitivity",
    "configsetting"
})
@XmlRootElement(name = "configsettings")
public class Configsettings {

    @XmlSchemaType(name = "anySimpleType")
    protected String bradyhrlimit;
    @XmlSchemaType(name = "string")
    protected TYPEflag asianlvhcriteria;
    @XmlSchemaType(name = "anySimpleType")
    protected String qualitystmts;
    @XmlSchemaType(name = "anySimpleType")
    protected String sensitivity;
    protected List<Configsetting> configsetting;

    /**
     * Gets the value of the bradyhrlimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBradyhrlimit() {
        return bradyhrlimit;
    }

    /**
     * Sets the value of the bradyhrlimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBradyhrlimit(String value) {
        this.bradyhrlimit = value;
    }

    /**
     * Gets the value of the asianlvhcriteria property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getAsianlvhcriteria() {
        return asianlvhcriteria;
    }

    /**
     * Sets the value of the asianlvhcriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setAsianlvhcriteria(TYPEflag value) {
        this.asianlvhcriteria = value;
    }

    /**
     * Gets the value of the qualitystmts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualitystmts() {
        return qualitystmts;
    }

    /**
     * Sets the value of the qualitystmts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualitystmts(String value) {
        this.qualitystmts = value;
    }

    /**
     * Gets the value of the sensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensitivity() {
        return sensitivity;
    }

    /**
     * Sets the value of the sensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensitivity(String value) {
        this.sensitivity = value;
    }

    /**
     * Gets the value of the configsetting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configsetting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigsetting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Configsetting }
     * 
     * 
     */
    public List<Configsetting> getConfigsetting() {
        if (configsetting == null) {
            configsetting = new ArrayList<Configsetting>();
        }
        return this.configsetting;
    }

}
