//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www3.medical.philips.com}crossleadmeasurements.elements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fixedmultpflag" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="multptestvalidflag" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="qrslikeartfflag" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="pacebeatmeasflag" type="{http://www3.medical.philips.com}TYPEflag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pacedetectleads",
    "pacepulses",
    "pacemode",
    "pacemalf",
    "pacemisc",
    "ectopicrhythm",
    "qtintdispersion",
    "numberofcomplexes",
    "numberofgroups",
    "beatclassification",
    "qamessagecodes",
    "qaactioncode",
    "pfrontaxis",
    "phorizaxis",
    "i40Frontaxis",
    "i40Horizaxis",
    "qrsfrontaxis",
    "qrshorizaxis",
    "t40Frontaxis",
    "t40Horizaxis",
    "stfrontaxis",
    "sthorizaxis",
    "tfrontaxis",
    "thorizaxis",
    "atrialrate",
    "lowventrate",
    "meanventrate",
    "highventrate",
    "meanprint",
    "meanprseg",
    "meanqrsdur",
    "meanqtint",
    "meanqtc",
    "deltawavecount",
    "deltawavepercent",
    "bigeminycount",
    "bigeminystring",
    "trigeminycount",
    "trigeminystring",
    "wenckcount",
    "wenckstring",
    "flutterfibcount",
    "leadreversalcode",
    "atrialrhythm",
    "atrialratepowerspect",
    "ventrhythm",
    "randomrrpercent",
    "regularrrpercent",
    "biggestrrgrouppercent",
    "biggestrrgroupvar",
    "nrrgroups",
    "bigemrrintvlacf",
    "trigemrrintvlacf",
    "fibfreqmhz",
    "fibampnv",
    "fibwidthmhz",
    "fibmedianfreqmhz",
    "afltcyclelen",
    "afltacfpeak",
    "afltacfpeakwidth",
    "constantpshapepct",
    "atrialrateirregpct",
    "transpcwrot",
    "transpinitangle",
    "transpinitmag",
    "transpmaxangle",
    "transpmaxmag",
    "transptermangle",
    "transptermmag",
    "transqrscwrot",
    "transqrsinitangle",
    "transqrsinitmag",
    "transqrsmaxangle",
    "transqrsmaxmag",
    "transqrstermangle",
    "transqrstermmag",
    "transtcwrot",
    "transtinitangle",
    "transtinitmag",
    "transtmaxangle",
    "transtmaxmag",
    "transttermangle",
    "transttermmag",
    "frontpcwrot",
    "frontpinitangle",
    "frontpinitmag",
    "frontpmaxangle",
    "frontpmaxmag",
    "frontptermangle",
    "frontptermmag",
    "frontqrscwrot",
    "frontqrsinitangle",
    "frontqrsinitmag",
    "frontqrsmaxangle",
    "frontqrsmaxmag",
    "frontqrstermangle",
    "frontqrstermmag",
    "fronttcwrot",
    "fronttinitangle",
    "fronttinitmag",
    "fronttmaxangle",
    "fronttmaxmag",
    "frontttermangle",
    "frontttermmag",
    "sagpcwrot",
    "sagpinitangle",
    "sagpinitmag",
    "sagpmaxangle",
    "sagpmaxmag",
    "sagptermangle",
    "sagptermmag",
    "sagqrscwrot",
    "sagqrsinitangle",
    "sagqrsinitmag",
    "sagqrsmaxangle",
    "sagqrsmaxmag",
    "sagqrstermangle",
    "sagqrstermmag",
    "sagtcwrot",
    "sagtinitangle",
    "sagtinitmag",
    "sagtmaxangle",
    "sagtmaxmag",
    "sagttermangle",
    "sagttermmag",
    "preexcitation",
    "beats",
    "analysiserror",
    "analysiserrormessage",
    "namedmeasurement"
})
@XmlRootElement(name = "crossleadmeasurements")
public class Crossleadmeasurements {

    @XmlList
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> pacedetectleads;
    protected Pacepulses pacepulses;
    @XmlSchemaType(name = "anySimpleType")
    protected String pacemode;
    @XmlSchemaType(name = "anySimpleType")
    protected String pacemalf;
    @XmlSchemaType(name = "anySimpleType")
    protected String pacemisc;
    @XmlSchemaType(name = "anySimpleType")
    protected String ectopicrhythm;
    @XmlSchemaType(name = "anySimpleType")
    protected String qtintdispersion;
    @XmlSchemaType(name = "anySimpleType")
    protected String numberofcomplexes;
    @XmlSchemaType(name = "anySimpleType")
    protected String numberofgroups;
    @XmlList
    @XmlElement(type = Integer.class)
    @XmlSchemaType(name = "anySimpleType")
    protected List<Integer> beatclassification;
    protected Qamessagecodes qamessagecodes;
    @XmlSchemaType(name = "string")
    protected TYPEactioncode qaactioncode;
    @XmlSchemaType(name = "anySimpleType")
    protected String pfrontaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String phorizaxis;
    @XmlElement(name = "i40frontaxis")
    @XmlSchemaType(name = "anySimpleType")
    protected String i40Frontaxis;
    @XmlElement(name = "i40horizaxis")
    @XmlSchemaType(name = "anySimpleType")
    protected String i40Horizaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String qrsfrontaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String qrshorizaxis;
    @XmlElement(name = "t40frontaxis")
    @XmlSchemaType(name = "anySimpleType")
    protected String t40Frontaxis;
    @XmlElement(name = "t40horizaxis")
    @XmlSchemaType(name = "anySimpleType")
    protected String t40Horizaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String stfrontaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String sthorizaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String tfrontaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String thorizaxis;
    @XmlSchemaType(name = "anySimpleType")
    protected String atrialrate;
    @XmlSchemaType(name = "anySimpleType")
    protected String lowventrate;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanventrate;
    @XmlSchemaType(name = "anySimpleType")
    protected String highventrate;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanprint;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanprseg;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanqrsdur;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanqtint;
    @XmlSchemaType(name = "anySimpleType")
    protected String meanqtc;
    @XmlSchemaType(name = "anySimpleType")
    protected String deltawavecount;
    @XmlSchemaType(name = "anySimpleType")
    protected String deltawavepercent;
    @XmlSchemaType(name = "anySimpleType")
    protected String bigeminycount;
    @XmlSchemaType(name = "anySimpleType")
    protected String bigeminystring;
    @XmlSchemaType(name = "anySimpleType")
    protected String trigeminycount;
    @XmlSchemaType(name = "anySimpleType")
    protected String trigeminystring;
    @XmlSchemaType(name = "anySimpleType")
    protected String wenckcount;
    @XmlSchemaType(name = "anySimpleType")
    protected String wenckstring;
    @XmlSchemaType(name = "anySimpleType")
    protected String flutterfibcount;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger leadreversalcode;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger atrialrhythm;
    @XmlSchemaType(name = "anySimpleType")
    protected String atrialratepowerspect;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ventrhythm;
    @XmlSchemaType(name = "anySimpleType")
    protected String randomrrpercent;
    @XmlSchemaType(name = "anySimpleType")
    protected String regularrrpercent;
    @XmlSchemaType(name = "anySimpleType")
    protected String biggestrrgrouppercent;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger biggestrrgroupvar;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger nrrgroups;
    @XmlSchemaType(name = "anySimpleType")
    protected String bigemrrintvlacf;
    @XmlSchemaType(name = "anySimpleType")
    protected String trigemrrintvlacf;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fibfreqmhz;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fibampnv;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fibwidthmhz;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fibmedianfreqmhz;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger afltcyclelen;
    @XmlSchemaType(name = "anySimpleType")
    protected String afltacfpeak;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger afltacfpeakwidth;
    @XmlSchemaType(name = "anySimpleType")
    protected String constantpshapepct;
    @XmlSchemaType(name = "anySimpleType")
    protected String atrialrateirregpct;
    @XmlSchemaType(name = "anySimpleType")
    protected String transpcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String transpinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transpinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transpmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transpmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transptermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transptermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrscwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrsinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrsinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrsmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrsmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrstermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transqrstermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transtcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String transtinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transtinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transtmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transtmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String transttermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String transttermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontpcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontpinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontpinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontpmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontpmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontptermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontptermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrscwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrsinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrsinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrsmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrsmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrstermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontqrstermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String fronttcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String fronttinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String fronttinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String fronttmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String fronttmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontttermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String frontttermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagpcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagpinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagpinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagpmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagpmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagptermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagptermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrscwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrsinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrsinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrsmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrsmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrstermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagqrstermmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagtcwrot;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagtinitangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagtinitmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagtmaxangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagtmaxmag;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagttermangle;
    @XmlSchemaType(name = "anySimpleType")
    protected String sagttermmag;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger preexcitation;
    protected Beats beats;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger analysiserror;
    protected String analysiserrormessage;
    protected List<Namedmeasurement> namedmeasurement;
    @XmlAttribute(name = "fixedmultpflag")
    protected TYPEflag fixedmultpflag;
    @XmlAttribute(name = "multptestvalidflag")
    protected TYPEflag multptestvalidflag;
    @XmlAttribute(name = "qrslikeartfflag")
    protected TYPEflag qrslikeartfflag;
    @XmlAttribute(name = "pacebeatmeasflag")
    protected TYPEflag pacebeatmeasflag;

    /**
     * Gets the value of the pacedetectleads property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pacedetectleads property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPacedetectleads().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPacedetectleads() {
        if (pacedetectleads == null) {
            pacedetectleads = new ArrayList<String>();
        }
        return this.pacedetectleads;
    }

    /**
     * Gets the value of the pacepulses property.
     * 
     * @return
     *     possible object is
     *     {@link Pacepulses }
     *     
     */
    public Pacepulses getPacepulses() {
        return pacepulses;
    }

    /**
     * Sets the value of the pacepulses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pacepulses }
     *     
     */
    public void setPacepulses(Pacepulses value) {
        this.pacepulses = value;
    }

    /**
     * Gets the value of the pacemode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacemode() {
        return pacemode;
    }

    /**
     * Sets the value of the pacemode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacemode(String value) {
        this.pacemode = value;
    }

    /**
     * Gets the value of the pacemalf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacemalf() {
        return pacemalf;
    }

    /**
     * Sets the value of the pacemalf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacemalf(String value) {
        this.pacemalf = value;
    }

    /**
     * Gets the value of the pacemisc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacemisc() {
        return pacemisc;
    }

    /**
     * Sets the value of the pacemisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacemisc(String value) {
        this.pacemisc = value;
    }

    /**
     * Gets the value of the ectopicrhythm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEctopicrhythm() {
        return ectopicrhythm;
    }

    /**
     * Sets the value of the ectopicrhythm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEctopicrhythm(String value) {
        this.ectopicrhythm = value;
    }

    /**
     * Gets the value of the qtintdispersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtintdispersion() {
        return qtintdispersion;
    }

    /**
     * Sets the value of the qtintdispersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtintdispersion(String value) {
        this.qtintdispersion = value;
    }

    /**
     * Gets the value of the numberofcomplexes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberofcomplexes() {
        return numberofcomplexes;
    }

    /**
     * Sets the value of the numberofcomplexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberofcomplexes(String value) {
        this.numberofcomplexes = value;
    }

    /**
     * Gets the value of the numberofgroups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberofgroups() {
        return numberofgroups;
    }

    /**
     * Sets the value of the numberofgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberofgroups(String value) {
        this.numberofgroups = value;
    }

    /**
     * Gets the value of the beatclassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beatclassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeatclassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getBeatclassification() {
        if (beatclassification == null) {
            beatclassification = new ArrayList<Integer>();
        }
        return this.beatclassification;
    }

    /**
     * Gets the value of the qamessagecodes property.
     * 
     * @return
     *     possible object is
     *     {@link Qamessagecodes }
     *     
     */
    public Qamessagecodes getQamessagecodes() {
        return qamessagecodes;
    }

    /**
     * Sets the value of the qamessagecodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qamessagecodes }
     *     
     */
    public void setQamessagecodes(Qamessagecodes value) {
        this.qamessagecodes = value;
    }

    /**
     * Gets the value of the qaactioncode property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEactioncode }
     *     
     */
    public TYPEactioncode getQaactioncode() {
        return qaactioncode;
    }

    /**
     * Sets the value of the qaactioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEactioncode }
     *     
     */
    public void setQaactioncode(TYPEactioncode value) {
        this.qaactioncode = value;
    }

    /**
     * Gets the value of the pfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfrontaxis() {
        return pfrontaxis;
    }

    /**
     * Sets the value of the pfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfrontaxis(String value) {
        this.pfrontaxis = value;
    }

    /**
     * Gets the value of the phorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhorizaxis() {
        return phorizaxis;
    }

    /**
     * Sets the value of the phorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhorizaxis(String value) {
        this.phorizaxis = value;
    }

    /**
     * Gets the value of the i40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI40Frontaxis() {
        return i40Frontaxis;
    }

    /**
     * Sets the value of the i40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI40Frontaxis(String value) {
        this.i40Frontaxis = value;
    }

    /**
     * Gets the value of the i40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI40Horizaxis() {
        return i40Horizaxis;
    }

    /**
     * Sets the value of the i40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI40Horizaxis(String value) {
        this.i40Horizaxis = value;
    }

    /**
     * Gets the value of the qrsfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrsfrontaxis() {
        return qrsfrontaxis;
    }

    /**
     * Sets the value of the qrsfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrsfrontaxis(String value) {
        this.qrsfrontaxis = value;
    }

    /**
     * Gets the value of the qrshorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrshorizaxis() {
        return qrshorizaxis;
    }

    /**
     * Sets the value of the qrshorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrshorizaxis(String value) {
        this.qrshorizaxis = value;
    }

    /**
     * Gets the value of the t40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT40Frontaxis() {
        return t40Frontaxis;
    }

    /**
     * Sets the value of the t40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT40Frontaxis(String value) {
        this.t40Frontaxis = value;
    }

    /**
     * Gets the value of the t40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT40Horizaxis() {
        return t40Horizaxis;
    }

    /**
     * Sets the value of the t40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT40Horizaxis(String value) {
        this.t40Horizaxis = value;
    }

    /**
     * Gets the value of the stfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfrontaxis() {
        return stfrontaxis;
    }

    /**
     * Sets the value of the stfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfrontaxis(String value) {
        this.stfrontaxis = value;
    }

    /**
     * Gets the value of the sthorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSthorizaxis() {
        return sthorizaxis;
    }

    /**
     * Sets the value of the sthorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSthorizaxis(String value) {
        this.sthorizaxis = value;
    }

    /**
     * Gets the value of the tfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTfrontaxis() {
        return tfrontaxis;
    }

    /**
     * Sets the value of the tfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTfrontaxis(String value) {
        this.tfrontaxis = value;
    }

    /**
     * Gets the value of the thorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThorizaxis() {
        return thorizaxis;
    }

    /**
     * Sets the value of the thorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThorizaxis(String value) {
        this.thorizaxis = value;
    }

    /**
     * Gets the value of the atrialrate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtrialrate() {
        return atrialrate;
    }

    /**
     * Sets the value of the atrialrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtrialrate(String value) {
        this.atrialrate = value;
    }

    /**
     * Gets the value of the lowventrate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowventrate() {
        return lowventrate;
    }

    /**
     * Sets the value of the lowventrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowventrate(String value) {
        this.lowventrate = value;
    }

    /**
     * Gets the value of the meanventrate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanventrate() {
        return meanventrate;
    }

    /**
     * Sets the value of the meanventrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanventrate(String value) {
        this.meanventrate = value;
    }

    /**
     * Gets the value of the highventrate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighventrate() {
        return highventrate;
    }

    /**
     * Sets the value of the highventrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighventrate(String value) {
        this.highventrate = value;
    }

    /**
     * Gets the value of the meanprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanprint() {
        return meanprint;
    }

    /**
     * Sets the value of the meanprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanprint(String value) {
        this.meanprint = value;
    }

    /**
     * Gets the value of the meanprseg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanprseg() {
        return meanprseg;
    }

    /**
     * Sets the value of the meanprseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanprseg(String value) {
        this.meanprseg = value;
    }

    /**
     * Gets the value of the meanqrsdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanqrsdur() {
        return meanqrsdur;
    }

    /**
     * Sets the value of the meanqrsdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanqrsdur(String value) {
        this.meanqrsdur = value;
    }

    /**
     * Gets the value of the meanqtint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanqtint() {
        return meanqtint;
    }

    /**
     * Sets the value of the meanqtint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanqtint(String value) {
        this.meanqtint = value;
    }

    /**
     * Gets the value of the meanqtc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanqtc() {
        return meanqtc;
    }

    /**
     * Sets the value of the meanqtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanqtc(String value) {
        this.meanqtc = value;
    }

    /**
     * Gets the value of the deltawavecount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeltawavecount() {
        return deltawavecount;
    }

    /**
     * Sets the value of the deltawavecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeltawavecount(String value) {
        this.deltawavecount = value;
    }

    /**
     * Gets the value of the deltawavepercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeltawavepercent() {
        return deltawavepercent;
    }

    /**
     * Sets the value of the deltawavepercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeltawavepercent(String value) {
        this.deltawavepercent = value;
    }

    /**
     * Gets the value of the bigeminycount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBigeminycount() {
        return bigeminycount;
    }

    /**
     * Sets the value of the bigeminycount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBigeminycount(String value) {
        this.bigeminycount = value;
    }

    /**
     * Gets the value of the bigeminystring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBigeminystring() {
        return bigeminystring;
    }

    /**
     * Sets the value of the bigeminystring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBigeminystring(String value) {
        this.bigeminystring = value;
    }

    /**
     * Gets the value of the trigeminycount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrigeminycount() {
        return trigeminycount;
    }

    /**
     * Sets the value of the trigeminycount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrigeminycount(String value) {
        this.trigeminycount = value;
    }

    /**
     * Gets the value of the trigeminystring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrigeminystring() {
        return trigeminystring;
    }

    /**
     * Sets the value of the trigeminystring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrigeminystring(String value) {
        this.trigeminystring = value;
    }

    /**
     * Gets the value of the wenckcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWenckcount() {
        return wenckcount;
    }

    /**
     * Sets the value of the wenckcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWenckcount(String value) {
        this.wenckcount = value;
    }

    /**
     * Gets the value of the wenckstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWenckstring() {
        return wenckstring;
    }

    /**
     * Sets the value of the wenckstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWenckstring(String value) {
        this.wenckstring = value;
    }

    /**
     * Gets the value of the flutterfibcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlutterfibcount() {
        return flutterfibcount;
    }

    /**
     * Sets the value of the flutterfibcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlutterfibcount(String value) {
        this.flutterfibcount = value;
    }

    /**
     * Gets the value of the leadreversalcode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeadreversalcode() {
        return leadreversalcode;
    }

    /**
     * Sets the value of the leadreversalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeadreversalcode(BigInteger value) {
        this.leadreversalcode = value;
    }

    /**
     * Gets the value of the atrialrhythm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAtrialrhythm() {
        return atrialrhythm;
    }

    /**
     * Sets the value of the atrialrhythm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAtrialrhythm(BigInteger value) {
        this.atrialrhythm = value;
    }

    /**
     * Gets the value of the atrialratepowerspect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtrialratepowerspect() {
        return atrialratepowerspect;
    }

    /**
     * Sets the value of the atrialratepowerspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtrialratepowerspect(String value) {
        this.atrialratepowerspect = value;
    }

    /**
     * Gets the value of the ventrhythm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVentrhythm() {
        return ventrhythm;
    }

    /**
     * Sets the value of the ventrhythm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVentrhythm(BigInteger value) {
        this.ventrhythm = value;
    }

    /**
     * Gets the value of the randomrrpercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRandomrrpercent() {
        return randomrrpercent;
    }

    /**
     * Sets the value of the randomrrpercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRandomrrpercent(String value) {
        this.randomrrpercent = value;
    }

    /**
     * Gets the value of the regularrrpercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegularrrpercent() {
        return regularrrpercent;
    }

    /**
     * Sets the value of the regularrrpercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegularrrpercent(String value) {
        this.regularrrpercent = value;
    }

    /**
     * Gets the value of the biggestrrgrouppercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiggestrrgrouppercent() {
        return biggestrrgrouppercent;
    }

    /**
     * Sets the value of the biggestrrgrouppercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiggestrrgrouppercent(String value) {
        this.biggestrrgrouppercent = value;
    }

    /**
     * Gets the value of the biggestrrgroupvar property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBiggestrrgroupvar() {
        return biggestrrgroupvar;
    }

    /**
     * Sets the value of the biggestrrgroupvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBiggestrrgroupvar(BigInteger value) {
        this.biggestrrgroupvar = value;
    }

    /**
     * Gets the value of the nrrgroups property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNrrgroups() {
        return nrrgroups;
    }

    /**
     * Sets the value of the nrrgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNrrgroups(BigInteger value) {
        this.nrrgroups = value;
    }

    /**
     * Gets the value of the bigemrrintvlacf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBigemrrintvlacf() {
        return bigemrrintvlacf;
    }

    /**
     * Sets the value of the bigemrrintvlacf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBigemrrintvlacf(String value) {
        this.bigemrrintvlacf = value;
    }

    /**
     * Gets the value of the trigemrrintvlacf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrigemrrintvlacf() {
        return trigemrrintvlacf;
    }

    /**
     * Sets the value of the trigemrrintvlacf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrigemrrintvlacf(String value) {
        this.trigemrrintvlacf = value;
    }

    /**
     * Gets the value of the fibfreqmhz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFibfreqmhz() {
        return fibfreqmhz;
    }

    /**
     * Sets the value of the fibfreqmhz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFibfreqmhz(BigInteger value) {
        this.fibfreqmhz = value;
    }

    /**
     * Gets the value of the fibampnv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFibampnv() {
        return fibampnv;
    }

    /**
     * Sets the value of the fibampnv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFibampnv(BigInteger value) {
        this.fibampnv = value;
    }

    /**
     * Gets the value of the fibwidthmhz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFibwidthmhz() {
        return fibwidthmhz;
    }

    /**
     * Sets the value of the fibwidthmhz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFibwidthmhz(BigInteger value) {
        this.fibwidthmhz = value;
    }

    /**
     * Gets the value of the fibmedianfreqmhz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFibmedianfreqmhz() {
        return fibmedianfreqmhz;
    }

    /**
     * Sets the value of the fibmedianfreqmhz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFibmedianfreqmhz(BigInteger value) {
        this.fibmedianfreqmhz = value;
    }

    /**
     * Gets the value of the afltcyclelen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAfltcyclelen() {
        return afltcyclelen;
    }

    /**
     * Sets the value of the afltcyclelen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAfltcyclelen(BigInteger value) {
        this.afltcyclelen = value;
    }

    /**
     * Gets the value of the afltacfpeak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfltacfpeak() {
        return afltacfpeak;
    }

    /**
     * Sets the value of the afltacfpeak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfltacfpeak(String value) {
        this.afltacfpeak = value;
    }

    /**
     * Gets the value of the afltacfpeakwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAfltacfpeakwidth() {
        return afltacfpeakwidth;
    }

    /**
     * Sets the value of the afltacfpeakwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAfltacfpeakwidth(BigInteger value) {
        this.afltacfpeakwidth = value;
    }

    /**
     * Gets the value of the constantpshapepct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstantpshapepct() {
        return constantpshapepct;
    }

    /**
     * Sets the value of the constantpshapepct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstantpshapepct(String value) {
        this.constantpshapepct = value;
    }

    /**
     * Gets the value of the atrialrateirregpct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtrialrateirregpct() {
        return atrialrateirregpct;
    }

    /**
     * Sets the value of the atrialrateirregpct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtrialrateirregpct(String value) {
        this.atrialrateirregpct = value;
    }

    /**
     * Gets the value of the transpcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranspcwrot() {
        return transpcwrot;
    }

    /**
     * Sets the value of the transpcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranspcwrot(String value) {
        this.transpcwrot = value;
    }

    /**
     * Gets the value of the transpinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranspinitangle() {
        return transpinitangle;
    }

    /**
     * Sets the value of the transpinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranspinitangle(String value) {
        this.transpinitangle = value;
    }

    /**
     * Gets the value of the transpinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranspinitmag() {
        return transpinitmag;
    }

    /**
     * Sets the value of the transpinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranspinitmag(String value) {
        this.transpinitmag = value;
    }

    /**
     * Gets the value of the transpmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranspmaxangle() {
        return transpmaxangle;
    }

    /**
     * Sets the value of the transpmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranspmaxangle(String value) {
        this.transpmaxangle = value;
    }

    /**
     * Gets the value of the transpmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranspmaxmag() {
        return transpmaxmag;
    }

    /**
     * Sets the value of the transpmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranspmaxmag(String value) {
        this.transpmaxmag = value;
    }

    /**
     * Gets the value of the transptermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransptermangle() {
        return transptermangle;
    }

    /**
     * Sets the value of the transptermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransptermangle(String value) {
        this.transptermangle = value;
    }

    /**
     * Gets the value of the transptermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransptermmag() {
        return transptermmag;
    }

    /**
     * Sets the value of the transptermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransptermmag(String value) {
        this.transptermmag = value;
    }

    /**
     * Gets the value of the transqrscwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrscwrot() {
        return transqrscwrot;
    }

    /**
     * Sets the value of the transqrscwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrscwrot(String value) {
        this.transqrscwrot = value;
    }

    /**
     * Gets the value of the transqrsinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrsinitangle() {
        return transqrsinitangle;
    }

    /**
     * Sets the value of the transqrsinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrsinitangle(String value) {
        this.transqrsinitangle = value;
    }

    /**
     * Gets the value of the transqrsinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrsinitmag() {
        return transqrsinitmag;
    }

    /**
     * Sets the value of the transqrsinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrsinitmag(String value) {
        this.transqrsinitmag = value;
    }

    /**
     * Gets the value of the transqrsmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrsmaxangle() {
        return transqrsmaxangle;
    }

    /**
     * Sets the value of the transqrsmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrsmaxangle(String value) {
        this.transqrsmaxangle = value;
    }

    /**
     * Gets the value of the transqrsmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrsmaxmag() {
        return transqrsmaxmag;
    }

    /**
     * Sets the value of the transqrsmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrsmaxmag(String value) {
        this.transqrsmaxmag = value;
    }

    /**
     * Gets the value of the transqrstermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrstermangle() {
        return transqrstermangle;
    }

    /**
     * Sets the value of the transqrstermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrstermangle(String value) {
        this.transqrstermangle = value;
    }

    /**
     * Gets the value of the transqrstermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransqrstermmag() {
        return transqrstermmag;
    }

    /**
     * Sets the value of the transqrstermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransqrstermmag(String value) {
        this.transqrstermmag = value;
    }

    /**
     * Gets the value of the transtcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstcwrot() {
        return transtcwrot;
    }

    /**
     * Sets the value of the transtcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstcwrot(String value) {
        this.transtcwrot = value;
    }

    /**
     * Gets the value of the transtinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstinitangle() {
        return transtinitangle;
    }

    /**
     * Sets the value of the transtinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstinitangle(String value) {
        this.transtinitangle = value;
    }

    /**
     * Gets the value of the transtinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstinitmag() {
        return transtinitmag;
    }

    /**
     * Sets the value of the transtinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstinitmag(String value) {
        this.transtinitmag = value;
    }

    /**
     * Gets the value of the transtmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstmaxangle() {
        return transtmaxangle;
    }

    /**
     * Sets the value of the transtmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstmaxangle(String value) {
        this.transtmaxangle = value;
    }

    /**
     * Gets the value of the transtmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstmaxmag() {
        return transtmaxmag;
    }

    /**
     * Sets the value of the transtmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstmaxmag(String value) {
        this.transtmaxmag = value;
    }

    /**
     * Gets the value of the transttermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransttermangle() {
        return transttermangle;
    }

    /**
     * Sets the value of the transttermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransttermangle(String value) {
        this.transttermangle = value;
    }

    /**
     * Gets the value of the transttermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransttermmag() {
        return transttermmag;
    }

    /**
     * Sets the value of the transttermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransttermmag(String value) {
        this.transttermmag = value;
    }

    /**
     * Gets the value of the frontpcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontpcwrot() {
        return frontpcwrot;
    }

    /**
     * Sets the value of the frontpcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontpcwrot(String value) {
        this.frontpcwrot = value;
    }

    /**
     * Gets the value of the frontpinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontpinitangle() {
        return frontpinitangle;
    }

    /**
     * Sets the value of the frontpinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontpinitangle(String value) {
        this.frontpinitangle = value;
    }

    /**
     * Gets the value of the frontpinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontpinitmag() {
        return frontpinitmag;
    }

    /**
     * Sets the value of the frontpinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontpinitmag(String value) {
        this.frontpinitmag = value;
    }

    /**
     * Gets the value of the frontpmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontpmaxangle() {
        return frontpmaxangle;
    }

    /**
     * Sets the value of the frontpmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontpmaxangle(String value) {
        this.frontpmaxangle = value;
    }

    /**
     * Gets the value of the frontpmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontpmaxmag() {
        return frontpmaxmag;
    }

    /**
     * Sets the value of the frontpmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontpmaxmag(String value) {
        this.frontpmaxmag = value;
    }

    /**
     * Gets the value of the frontptermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontptermangle() {
        return frontptermangle;
    }

    /**
     * Sets the value of the frontptermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontptermangle(String value) {
        this.frontptermangle = value;
    }

    /**
     * Gets the value of the frontptermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontptermmag() {
        return frontptermmag;
    }

    /**
     * Sets the value of the frontptermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontptermmag(String value) {
        this.frontptermmag = value;
    }

    /**
     * Gets the value of the frontqrscwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrscwrot() {
        return frontqrscwrot;
    }

    /**
     * Sets the value of the frontqrscwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrscwrot(String value) {
        this.frontqrscwrot = value;
    }

    /**
     * Gets the value of the frontqrsinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrsinitangle() {
        return frontqrsinitangle;
    }

    /**
     * Sets the value of the frontqrsinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrsinitangle(String value) {
        this.frontqrsinitangle = value;
    }

    /**
     * Gets the value of the frontqrsinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrsinitmag() {
        return frontqrsinitmag;
    }

    /**
     * Sets the value of the frontqrsinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrsinitmag(String value) {
        this.frontqrsinitmag = value;
    }

    /**
     * Gets the value of the frontqrsmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrsmaxangle() {
        return frontqrsmaxangle;
    }

    /**
     * Sets the value of the frontqrsmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrsmaxangle(String value) {
        this.frontqrsmaxangle = value;
    }

    /**
     * Gets the value of the frontqrsmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrsmaxmag() {
        return frontqrsmaxmag;
    }

    /**
     * Sets the value of the frontqrsmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrsmaxmag(String value) {
        this.frontqrsmaxmag = value;
    }

    /**
     * Gets the value of the frontqrstermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrstermangle() {
        return frontqrstermangle;
    }

    /**
     * Sets the value of the frontqrstermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrstermangle(String value) {
        this.frontqrstermangle = value;
    }

    /**
     * Gets the value of the frontqrstermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontqrstermmag() {
        return frontqrstermmag;
    }

    /**
     * Sets the value of the frontqrstermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontqrstermmag(String value) {
        this.frontqrstermmag = value;
    }

    /**
     * Gets the value of the fronttcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFronttcwrot() {
        return fronttcwrot;
    }

    /**
     * Sets the value of the fronttcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFronttcwrot(String value) {
        this.fronttcwrot = value;
    }

    /**
     * Gets the value of the fronttinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFronttinitangle() {
        return fronttinitangle;
    }

    /**
     * Sets the value of the fronttinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFronttinitangle(String value) {
        this.fronttinitangle = value;
    }

    /**
     * Gets the value of the fronttinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFronttinitmag() {
        return fronttinitmag;
    }

    /**
     * Sets the value of the fronttinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFronttinitmag(String value) {
        this.fronttinitmag = value;
    }

    /**
     * Gets the value of the fronttmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFronttmaxangle() {
        return fronttmaxangle;
    }

    /**
     * Sets the value of the fronttmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFronttmaxangle(String value) {
        this.fronttmaxangle = value;
    }

    /**
     * Gets the value of the fronttmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFronttmaxmag() {
        return fronttmaxmag;
    }

    /**
     * Sets the value of the fronttmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFronttmaxmag(String value) {
        this.fronttmaxmag = value;
    }

    /**
     * Gets the value of the frontttermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontttermangle() {
        return frontttermangle;
    }

    /**
     * Sets the value of the frontttermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontttermangle(String value) {
        this.frontttermangle = value;
    }

    /**
     * Gets the value of the frontttermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontttermmag() {
        return frontttermmag;
    }

    /**
     * Sets the value of the frontttermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontttermmag(String value) {
        this.frontttermmag = value;
    }

    /**
     * Gets the value of the sagpcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagpcwrot() {
        return sagpcwrot;
    }

    /**
     * Sets the value of the sagpcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagpcwrot(String value) {
        this.sagpcwrot = value;
    }

    /**
     * Gets the value of the sagpinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagpinitangle() {
        return sagpinitangle;
    }

    /**
     * Sets the value of the sagpinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagpinitangle(String value) {
        this.sagpinitangle = value;
    }

    /**
     * Gets the value of the sagpinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagpinitmag() {
        return sagpinitmag;
    }

    /**
     * Sets the value of the sagpinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagpinitmag(String value) {
        this.sagpinitmag = value;
    }

    /**
     * Gets the value of the sagpmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagpmaxangle() {
        return sagpmaxangle;
    }

    /**
     * Sets the value of the sagpmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagpmaxangle(String value) {
        this.sagpmaxangle = value;
    }

    /**
     * Gets the value of the sagpmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagpmaxmag() {
        return sagpmaxmag;
    }

    /**
     * Sets the value of the sagpmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagpmaxmag(String value) {
        this.sagpmaxmag = value;
    }

    /**
     * Gets the value of the sagptermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagptermangle() {
        return sagptermangle;
    }

    /**
     * Sets the value of the sagptermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagptermangle(String value) {
        this.sagptermangle = value;
    }

    /**
     * Gets the value of the sagptermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagptermmag() {
        return sagptermmag;
    }

    /**
     * Sets the value of the sagptermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagptermmag(String value) {
        this.sagptermmag = value;
    }

    /**
     * Gets the value of the sagqrscwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrscwrot() {
        return sagqrscwrot;
    }

    /**
     * Sets the value of the sagqrscwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrscwrot(String value) {
        this.sagqrscwrot = value;
    }

    /**
     * Gets the value of the sagqrsinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrsinitangle() {
        return sagqrsinitangle;
    }

    /**
     * Sets the value of the sagqrsinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrsinitangle(String value) {
        this.sagqrsinitangle = value;
    }

    /**
     * Gets the value of the sagqrsinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrsinitmag() {
        return sagqrsinitmag;
    }

    /**
     * Sets the value of the sagqrsinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrsinitmag(String value) {
        this.sagqrsinitmag = value;
    }

    /**
     * Gets the value of the sagqrsmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrsmaxangle() {
        return sagqrsmaxangle;
    }

    /**
     * Sets the value of the sagqrsmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrsmaxangle(String value) {
        this.sagqrsmaxangle = value;
    }

    /**
     * Gets the value of the sagqrsmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrsmaxmag() {
        return sagqrsmaxmag;
    }

    /**
     * Sets the value of the sagqrsmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrsmaxmag(String value) {
        this.sagqrsmaxmag = value;
    }

    /**
     * Gets the value of the sagqrstermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrstermangle() {
        return sagqrstermangle;
    }

    /**
     * Sets the value of the sagqrstermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrstermangle(String value) {
        this.sagqrstermangle = value;
    }

    /**
     * Gets the value of the sagqrstermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagqrstermmag() {
        return sagqrstermmag;
    }

    /**
     * Sets the value of the sagqrstermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagqrstermmag(String value) {
        this.sagqrstermmag = value;
    }

    /**
     * Gets the value of the sagtcwrot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagtcwrot() {
        return sagtcwrot;
    }

    /**
     * Sets the value of the sagtcwrot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagtcwrot(String value) {
        this.sagtcwrot = value;
    }

    /**
     * Gets the value of the sagtinitangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagtinitangle() {
        return sagtinitangle;
    }

    /**
     * Sets the value of the sagtinitangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagtinitangle(String value) {
        this.sagtinitangle = value;
    }

    /**
     * Gets the value of the sagtinitmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagtinitmag() {
        return sagtinitmag;
    }

    /**
     * Sets the value of the sagtinitmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagtinitmag(String value) {
        this.sagtinitmag = value;
    }

    /**
     * Gets the value of the sagtmaxangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagtmaxangle() {
        return sagtmaxangle;
    }

    /**
     * Sets the value of the sagtmaxangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagtmaxangle(String value) {
        this.sagtmaxangle = value;
    }

    /**
     * Gets the value of the sagtmaxmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagtmaxmag() {
        return sagtmaxmag;
    }

    /**
     * Sets the value of the sagtmaxmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagtmaxmag(String value) {
        this.sagtmaxmag = value;
    }

    /**
     * Gets the value of the sagttermangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagttermangle() {
        return sagttermangle;
    }

    /**
     * Sets the value of the sagttermangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagttermangle(String value) {
        this.sagttermangle = value;
    }

    /**
     * Gets the value of the sagttermmag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSagttermmag() {
        return sagttermmag;
    }

    /**
     * Sets the value of the sagttermmag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSagttermmag(String value) {
        this.sagttermmag = value;
    }

    /**
     * Gets the value of the preexcitation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPreexcitation() {
        return preexcitation;
    }

    /**
     * Sets the value of the preexcitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPreexcitation(BigInteger value) {
        this.preexcitation = value;
    }

    /**
     * Gets the value of the beats property.
     * 
     * @return
     *     possible object is
     *     {@link Beats }
     *     
     */
    public Beats getBeats() {
        return beats;
    }

    /**
     * Sets the value of the beats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beats }
     *     
     */
    public void setBeats(Beats value) {
        this.beats = value;
    }

    /**
     * Gets the value of the analysiserror property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnalysiserror() {
        return analysiserror;
    }

    /**
     * Sets the value of the analysiserror property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnalysiserror(BigInteger value) {
        this.analysiserror = value;
    }

    /**
     * Gets the value of the analysiserrormessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysiserrormessage() {
        return analysiserrormessage;
    }

    /**
     * Sets the value of the analysiserrormessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysiserrormessage(String value) {
        this.analysiserrormessage = value;
    }

    /**
     * Gets the value of the namedmeasurement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namedmeasurement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamedmeasurement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Namedmeasurement }
     * 
     * 
     */
    public List<Namedmeasurement> getNamedmeasurement() {
        if (namedmeasurement == null) {
            namedmeasurement = new ArrayList<Namedmeasurement>();
        }
        return this.namedmeasurement;
    }

    /**
     * Gets the value of the fixedmultpflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getFixedmultpflag() {
        return fixedmultpflag;
    }

    /**
     * Sets the value of the fixedmultpflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setFixedmultpflag(TYPEflag value) {
        this.fixedmultpflag = value;
    }

    /**
     * Gets the value of the multptestvalidflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getMultptestvalidflag() {
        return multptestvalidflag;
    }

    /**
     * Sets the value of the multptestvalidflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setMultptestvalidflag(TYPEflag value) {
        this.multptestvalidflag = value;
    }

    /**
     * Gets the value of the qrslikeartfflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getQrslikeartfflag() {
        return qrslikeartfflag;
    }

    /**
     * Sets the value of the qrslikeartfflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setQrslikeartfflag(TYPEflag value) {
        this.qrslikeartfflag = value;
    }

    /**
     * Gets the value of the pacebeatmeasflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getPacebeatmeasflag() {
        return pacebeatmeasflag;
    }

    /**
     * Sets the value of the pacebeatmeasflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setPacebeatmeasflag(TYPEflag value) {
        this.pacebeatmeasflag = value;
    }

}
