//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}crossleadmeasurements" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}groupmeasurements" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}leadmeasurements" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}configsettings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="measurementversion" use="required" type="{http://www3.medical.philips.com}TYPEmeasurementversion" />
 *       &lt;attribute name="custommeasurementversion" type="{http://www3.medical.philips.com}TYPEcustommeasurementversion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crossleadmeasurements",
    "groupmeasurements",
    "leadmeasurements",
    "configsettings"
})
@XmlRootElement(name = "internalmeasurements")
public class Internalmeasurements {

    protected Crossleadmeasurements crossleadmeasurements;
    protected Groupmeasurements groupmeasurements;
    protected Leadmeasurements leadmeasurements;
    protected Configsettings configsettings;
    @XmlAttribute(name = "date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlAttribute(name = "measurementversion", required = true)
    protected String measurementversion;
    @XmlAttribute(name = "custommeasurementversion")
    protected String custommeasurementversion;

    /**
     * Gets the value of the crossleadmeasurements property.
     * 
     * @return
     *     possible object is
     *     {@link Crossleadmeasurements }
     *     
     */
    public Crossleadmeasurements getCrossleadmeasurements() {
        return crossleadmeasurements;
    }

    /**
     * Sets the value of the crossleadmeasurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Crossleadmeasurements }
     *     
     */
    public void setCrossleadmeasurements(Crossleadmeasurements value) {
        this.crossleadmeasurements = value;
    }

    /**
     * Gets the value of the groupmeasurements property.
     * 
     * @return
     *     possible object is
     *     {@link Groupmeasurements }
     *     
     */
    public Groupmeasurements getGroupmeasurements() {
        return groupmeasurements;
    }

    /**
     * Sets the value of the groupmeasurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Groupmeasurements }
     *     
     */
    public void setGroupmeasurements(Groupmeasurements value) {
        this.groupmeasurements = value;
    }

    /**
     * Gets the value of the leadmeasurements property.
     * 
     * @return
     *     possible object is
     *     {@link Leadmeasurements }
     *     
     */
    public Leadmeasurements getLeadmeasurements() {
        return leadmeasurements;
    }

    /**
     * Sets the value of the leadmeasurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leadmeasurements }
     *     
     */
    public void setLeadmeasurements(Leadmeasurements value) {
        this.leadmeasurements = value;
    }

    /**
     * Gets the value of the configsettings property.
     * 
     * @return
     *     possible object is
     *     {@link Configsettings }
     *     
     */
    public Configsettings getConfigsettings() {
        return configsettings;
    }

    /**
     * Sets the value of the configsettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configsettings }
     *     
     */
    public void setConfigsettings(Configsettings value) {
        this.configsettings = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the measurementversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementversion() {
        return measurementversion;
    }

    /**
     * Sets the value of the measurementversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementversion(String value) {
        this.measurementversion = value;
    }

    /**
     * Gets the value of the custommeasurementversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustommeasurementversion() {
        return custommeasurementversion;
    }

    /**
     * Sets the value of the custommeasurementversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustommeasurementversion(String value) {
        this.custommeasurementversion = value;
    }

}
