//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="otherECG" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www3.medical.philips.com}TYPEotherECGtype"/>
 *                   &lt;element name="documentname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{http://www3.medical.philips.com}severity" minOccurs="0"/>
 *                   &lt;element name="mdsignatureline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="other" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                 &lt;attribute name="status" type="{http://www3.medical.philips.com}TYPErestingecgstatus" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otherECG"
})
@XmlRootElement(name = "otherECGs")
public class OtherECGs {

    protected List<OtherECGs.OtherECG> otherECG;

    /**
     * Gets the value of the otherECG property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherECG property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherECG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherECGs.OtherECG }
     * 
     * 
     */
    public List<OtherECGs.OtherECG> getOtherECG() {
        if (otherECG == null) {
            otherECG = new ArrayList<OtherECGs.OtherECG>();
        }
        return this.otherECG;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www3.medical.philips.com}TYPEotherECGtype"/>
     *         &lt;element name="documentname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{http://www3.medical.philips.com}severity" minOccurs="0"/>
     *         &lt;element name="mdsignatureline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="other" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
     *       &lt;attribute name="status" type="{http://www3.medical.philips.com}TYPErestingecgstatus" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "documentname",
        "severity",
        "mdsignatureline",
        "other"
    })
    public static class OtherECG {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TYPEotherECGtype type;
        @XmlElement(required = true)
        protected String documentname;
        protected Severity severity;
        protected String mdsignatureline;
        protected List<OtherECGs.OtherECG.Other> other;
        @XmlAttribute(name = "date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlAttribute(name = "time", required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar time;
        @XmlAttribute(name = "status")
        protected TYPErestingecgstatus status;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEotherECGtype }
         *     
         */
        public TYPEotherECGtype getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEotherECGtype }
         *     
         */
        public void setType(TYPEotherECGtype value) {
            this.type = value;
        }

        /**
         * Gets the value of the documentname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentname() {
            return documentname;
        }

        /**
         * Sets the value of the documentname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentname(String value) {
            this.documentname = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link Severity }
         *     
         */
        public Severity getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Severity }
         *     
         */
        public void setSeverity(Severity value) {
            this.severity = value;
        }

        /**
         * Gets the value of the mdsignatureline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMdsignatureline() {
            return mdsignatureline;
        }

        /**
         * Sets the value of the mdsignatureline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMdsignatureline(String value) {
            this.mdsignatureline = value;
        }

        /**
         * Gets the value of the other property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the other property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOther().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OtherECGs.OtherECG.Other }
         * 
         * 
         */
        public List<OtherECGs.OtherECG.Other> getOther() {
            if (other == null) {
                other = new ArrayList<OtherECGs.OtherECG.Other>();
            }
            return this.other;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTime(XMLGregorianCalendar value) {
            this.time = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link TYPErestingecgstatus }
         *     
         */
        public TYPErestingecgstatus getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPErestingecgstatus }
         *     
         */
        public void setStatus(TYPErestingecgstatus value) {
            this.status = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Other {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "label", required = true)
            protected String label;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

        }

    }

}
