//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}reportlabel"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportdescription"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportformat"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportgain"/>
 *         &lt;element ref="{http://www3.medical.philips.com}reportbandwidth"/>
 *         &lt;element name="other" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="original" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="userid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="other" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportlabel",
    "reportdescription",
    "reportformat",
    "reportgain",
    "reportbandwidth",
    "other"
})
@XmlRootElement(name = "savedreportinfo")
public class Savedreportinfo {

    @XmlElement(required = true)
    protected String reportlabel;
    @XmlElement(required = true)
    protected String reportdescription;
    @XmlElement(required = true)
    protected Reportformat reportformat;
    @XmlElement(required = true)
    protected Reportgain reportgain;
    @XmlElement(required = true)
    protected Reportbandwidth reportbandwidth;
    protected List<Savedreportinfo.Other> other;
    @XmlAttribute(name = "date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlAttribute(name = "original")
    protected TYPEflag original;
    @XmlAttribute(name = "userid")
    protected String userid;
    @XmlAttribute(name = "other")
    protected String otherAttribute;

    /**
     * Gets the value of the reportlabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportlabel() {
        return reportlabel;
    }

    /**
     * Sets the value of the reportlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportlabel(String value) {
        this.reportlabel = value;
    }

    /**
     * Gets the value of the reportdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportdescription() {
        return reportdescription;
    }

    /**
     * Sets the value of the reportdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportdescription(String value) {
        this.reportdescription = value;
    }

    /**
     * Gets the value of the reportformat property.
     * 
     * @return
     *     possible object is
     *     {@link Reportformat }
     *     
     */
    public Reportformat getReportformat() {
        return reportformat;
    }

    /**
     * Sets the value of the reportformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportformat }
     *     
     */
    public void setReportformat(Reportformat value) {
        this.reportformat = value;
    }

    /**
     * Gets the value of the reportgain property.
     * 
     * @return
     *     possible object is
     *     {@link Reportgain }
     *     
     */
    public Reportgain getReportgain() {
        return reportgain;
    }

    /**
     * Sets the value of the reportgain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportgain }
     *     
     */
    public void setReportgain(Reportgain value) {
        this.reportgain = value;
    }

    /**
     * Gets the value of the reportbandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Reportbandwidth }
     *     
     */
    public Reportbandwidth getReportbandwidth() {
        return reportbandwidth;
    }

    /**
     * Sets the value of the reportbandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportbandwidth }
     *     
     */
    public void setReportbandwidth(Reportbandwidth value) {
        this.reportbandwidth = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the other property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOther().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Savedreportinfo.Other }
     * 
     * 
     */
    public List<Savedreportinfo.Other> getOther() {
        if (other == null) {
            other = new ArrayList<Savedreportinfo.Other>();
        }
        return this.other;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the original property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getOriginal() {
        return original;
    }

    /**
     * Sets the value of the original property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setOriginal(TYPEflag value) {
        this.original = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the otherAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherAttribute() {
        return otherAttribute;
    }

    /**
     * Sets the value of the otherAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherAttribute(String value) {
        this.otherAttribute = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Other {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "label", required = true)
        protected String label;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }

}
