//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 08:44:39 PM EDT 
//


package org.sierraecg.schema.jaxb._1_04;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}samplingrate"/>
 *         &lt;element ref="{http://www3.medical.philips.com}resolution"/>
 *         &lt;element ref="{http://www3.medical.philips.com}hipass"/>
 *         &lt;element ref="{http://www3.medical.philips.com}lowpass"/>
 *         &lt;element ref="{http://www3.medical.philips.com}acsetting" minOccurs="0"/>
 *         &lt;element name="notchfiltered" type="{http://www3.medical.philips.com}TYPEflag" minOccurs="0"/>
 *         &lt;element name="notchfilterfreqs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="artfiltered" type="{http://www3.medical.philips.com}TYPEflag" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}acquisitiontype"/>
 *         &lt;element name="otheracquisitioninfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}bitspersample"/>
 *         &lt;element ref="{http://www3.medical.philips.com}signaloffset"/>
 *         &lt;element ref="{http://www3.medical.philips.com}signalsigned"/>
 *         &lt;element ref="{http://www3.medical.philips.com}numberchannelsallocated"/>
 *         &lt;element ref="{http://www3.medical.philips.com}numberchannelsvalid"/>
 *         &lt;element ref="{http://www3.medical.philips.com}electrodeplacement"/>
 *         &lt;element name="otherplacementinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www3.medical.philips.com}derivedleads" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "samplingrate",
    "resolution",
    "hipass",
    "lowpass",
    "acsetting",
    "notchfiltered",
    "notchfilterfreqs",
    "artfiltered",
    "acquisitiontype",
    "otheracquisitioninfo",
    "bitspersample",
    "signaloffset",
    "signalsigned",
    "numberchannelsallocated",
    "numberchannelsvalid",
    "electrodeplacement",
    "otherplacementinfo",
    "derivedleads"
})
@XmlRootElement(name = "signalcharacteristics")
public class Signalcharacteristics {

    protected float samplingrate;
    protected float resolution;
    protected float hipass;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lowpass;
    protected String acsetting;
    @XmlSchemaType(name = "string")
    protected TYPEflag notchfiltered;
    protected String notchfilterfreqs;
    @XmlSchemaType(name = "string")
    protected TYPEflag artfiltered;
    @XmlElement(required = true)
    protected String acquisitiontype;
    protected String otheracquisitioninfo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger bitspersample;
    @XmlElement(required = true)
    protected BigInteger signaloffset;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TYPEflag signalsigned;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberchannelsallocated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberchannelsvalid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TYPEelectrodeplacement electrodeplacement;
    protected String otherplacementinfo;
    protected TYPEderivedleads derivedleads;

    /**
     * Gets the value of the samplingrate property.
     * 
     */
    public float getSamplingrate() {
        return samplingrate;
    }

    /**
     * Sets the value of the samplingrate property.
     * 
     */
    public void setSamplingrate(float value) {
        this.samplingrate = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     */
    public float getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     */
    public void setResolution(float value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the hipass property.
     * 
     */
    public float getHipass() {
        return hipass;
    }

    /**
     * Sets the value of the hipass property.
     * 
     */
    public void setHipass(float value) {
        this.hipass = value;
    }

    /**
     * Gets the value of the lowpass property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLowpass() {
        return lowpass;
    }

    /**
     * Sets the value of the lowpass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLowpass(BigInteger value) {
        this.lowpass = value;
    }

    /**
     * Gets the value of the acsetting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcsetting() {
        return acsetting;
    }

    /**
     * Sets the value of the acsetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcsetting(String value) {
        this.acsetting = value;
    }

    /**
     * Gets the value of the notchfiltered property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getNotchfiltered() {
        return notchfiltered;
    }

    /**
     * Sets the value of the notchfiltered property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setNotchfiltered(TYPEflag value) {
        this.notchfiltered = value;
    }

    /**
     * Gets the value of the notchfilterfreqs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotchfilterfreqs() {
        return notchfilterfreqs;
    }

    /**
     * Sets the value of the notchfilterfreqs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotchfilterfreqs(String value) {
        this.notchfilterfreqs = value;
    }

    /**
     * Gets the value of the artfiltered property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getArtfiltered() {
        return artfiltered;
    }

    /**
     * Sets the value of the artfiltered property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setArtfiltered(TYPEflag value) {
        this.artfiltered = value;
    }

    /**
     * Gets the value of the acquisitiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitiontype() {
        return acquisitiontype;
    }

    /**
     * Sets the value of the acquisitiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitiontype(String value) {
        this.acquisitiontype = value;
    }

    /**
     * Gets the value of the otheracquisitioninfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtheracquisitioninfo() {
        return otheracquisitioninfo;
    }

    /**
     * Sets the value of the otheracquisitioninfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtheracquisitioninfo(String value) {
        this.otheracquisitioninfo = value;
    }

    /**
     * Gets the value of the bitspersample property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitspersample() {
        return bitspersample;
    }

    /**
     * Sets the value of the bitspersample property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitspersample(BigInteger value) {
        this.bitspersample = value;
    }

    /**
     * Gets the value of the signaloffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSignaloffset() {
        return signaloffset;
    }

    /**
     * Sets the value of the signaloffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSignaloffset(BigInteger value) {
        this.signaloffset = value;
    }

    /**
     * Gets the value of the signalsigned property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getSignalsigned() {
        return signalsigned;
    }

    /**
     * Sets the value of the signalsigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setSignalsigned(TYPEflag value) {
        this.signalsigned = value;
    }

    /**
     * Gets the value of the numberchannelsallocated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberchannelsallocated() {
        return numberchannelsallocated;
    }

    /**
     * Sets the value of the numberchannelsallocated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberchannelsallocated(BigInteger value) {
        this.numberchannelsallocated = value;
    }

    /**
     * Gets the value of the numberchannelsvalid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberchannelsvalid() {
        return numberchannelsvalid;
    }

    /**
     * Sets the value of the numberchannelsvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberchannelsvalid(BigInteger value) {
        this.numberchannelsvalid = value;
    }

    /**
     * Gets the value of the electrodeplacement property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEelectrodeplacement }
     *     
     */
    public TYPEelectrodeplacement getElectrodeplacement() {
        return electrodeplacement;
    }

    /**
     * Sets the value of the electrodeplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEelectrodeplacement }
     *     
     */
    public void setElectrodeplacement(TYPEelectrodeplacement value) {
        this.electrodeplacement = value;
    }

    /**
     * Gets the value of the otherplacementinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherplacementinfo() {
        return otherplacementinfo;
    }

    /**
     * Sets the value of the otherplacementinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherplacementinfo(String value) {
        this.otherplacementinfo = value;
    }

    /**
     * Gets the value of the derivedleads property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEderivedleads }
     *     
     */
    public TYPEderivedleads getDerivedleads() {
        return derivedleads;
    }

    /**
     * Sets the value of the derivedleads property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEderivedleads }
     *     
     */
    public void setDerivedleads(TYPEderivedleads value) {
        this.derivedleads = value;
    }

}
