#
# sierraecg NodeJS CI job
#
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'master'
    paths:
      - 'sierraecg-js/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Cover the supported NodeJS versions
        node-version: ['18.x', '20.x', '22.0']

    steps:
    - uses: actions/checkout@v4    
    - uses: actions/setup-node@v4
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run-script lint
    - run: npm run-script ci
